In [44]:
import numpy as np

In [ ]:
#Utwórz w zmiennej a jednowymiarową tablicę z elementami od 0 do 19. Hint: Służy do tego metoda np.arange

In [4]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#Wyświetl kształt tej tablicy. Hint: służy do tego właściwość shape

In [16]:
a.shape

(20,)

In [ ]:
 #Wyświetl zerowy element tablicy. Wyświetl czwarty element tablicy. Hint: Korzystaj z [] i numeruj od 0

In [9]:
a[0]

0

In [15]:
a[4]

4

In [14]:
#Zmień kształt tablicy na 2x10. Wynik przekształcenia zapisz w a. Potem ponownie sprawdź kształt i wyświetl zawartość tablicy.
#Hint: Skorzystaj z metody reshape(...)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
a =np.reshape(a,(2,10))

In [19]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
#Wyświetl element zerowy z przekształconej w poprzednim kroku tablicy. Czy jest to ten sam element co poprzednio?

In [20]:
a[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#(Uwaga - tu będzie błąd, ale na błędach człowiek się uczy, więc to dobrze). Wyświetl czwarty element z tablicy a

In [21]:
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 2

In [ ]:
8. #A teraz zróbmy to poprawnie. Z tablicy a wyświetl czwarty element znajdujący się w zerowym wierszu. Hint: Musisz dwa razy 
#skorzystać z [][]

In [22]:
a[0][4]

4

In [ ]:
#Zmień kształt tablicy a na 2x5x2

In [28]:
b = a.reshape(2,5,2)

In [29]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [30]:
b.shape

(2, 5, 2)

In [31]:
b[0]

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
b[0][4]

array([8, 9])

In [33]:
b[0][4][1]

9

In [ ]:
#12. Tworząc tablicę, możesz od razu definiować jej kształt. Utwórz tablicę b korzystając
#z parametrów przekazywanych do metody array lub wywołując odpowiednie metody dla już istniejącej tablicy, 
#tak aby zawierała ona elementy parzyste od 0 do 40 o kształcie 4x5

In [48]:
x = [number for number in range(40) if number % 2 == 0]
x

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

In [49]:
c =np.array(x).reshape(4, 5)

In [50]:
c

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [ ]:
#a_python_list =  [2**x for x in range(10)]

#tworzy standardową pythonową listę dziesięciu kolejnych potęg dwójki. W oparciu o tą listę utwórz obiekt array c1

In [55]:
a_python_list =  [2**x for x in range(10)]
c1 =np.array(a_python_list)
c1

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [ ]:
#14. To może się wydawać trochę dziwne, ale czasami w uczeniu maszynowym potrzebne są bardzo specyficzne obiekty array. 
#W tym zadaniu utworzysz takie "dziwaczne" tablice

In [ ]:
#Utwórz tablicę zero_array składającą się z 10 zer. Hint: Skorzystaj z metody zeros

In [58]:
zero_array=np.zeros((1,10))
zero_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#Utwórz tablicę one_array składającą się z 10 jedynek. Hint: Skorzystaj z metody ones

In [59]:
one_array=np.ones((1,10))
one_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
#Utwórz tablicę empty_array składającą się ze 100  byle-jakich-liczb. Hint skorzystaj z metody empty
#Ta metoda tworzy tablicę, która zawiera to, co akurat było w pamięci. Wielokrotne uruchamianie w/w 
#polecenia może dawać różne wyniki, ale to nie jest jakiś świetny sposób na generowanie liczb losowych

In [63]:
empty_array =np.empty((1,100))
empty_array

array([[0.00000000e+000, 0.00000000e+000, 4.94065646e-324,
        6.95264024e-310, 4.69362364e-322, 1.13651414e-311,
        1.13651414e-311, 1.13651414e-311, 1.13651414e-311,
        1.13651414e-311, 1.13651414e-311, 1.13651414e-311,
        1.13651414e-311, 1.13651414e-311, 1.13651414e-311,
        1.13651414e-311, 1.13651414e-311, 1.13651414e-311,
        1.13651414e-311, 1.13651414e-311, 1.13651414e-311,
        1.13651414e-311, 1.13651414e-311, 1.13651414e-311,
        1.13651414e-311, 1.13651414e-311, 1.13651414e-311,
        1.13651414e-311, 1.13651414e-311, 1.13651414e-311,
        1.13651414e-311, 1.13651414e-311, 1.13651414e-311,
        1.13651414e-311, 1.13651414e-311, 1.13651414e-311,
        1.13651414e-311, 1.13651414e-311, 1.13651414e-311,
        1.13651415e-311, 1.13651415e-311, 1.13651415e-311,
        1.13651415e-311, 1.13651415e-311, 1.13651415e-311,
        1.13651415e-311, 1.13651415e-311, 1.13651415e-311,
        1.13651415e-311, 1.13651415e-311, 1.13651415e-31

In [ ]:
#Utwórz tablicę linspace_array zawierającą 5 elementów, która jako zerową wartość ma 100, jako ostatnią ma wartość 200, i wszystkie elementy różnią się od siebie o tyle samo. 
#Hint: Skorzystaj z metody linspace

In [64]:
linspace_array = np.linspace(100, 200, 5)
print(linspace_array)

[100. 125. 150. 175. 200.]


In [ ]:
#Utwórz tablicę random_array składającą się z 10 losowych liczb. Hint: Skorzystaj z metody np.random.random

In [65]:
random_array = np.random.random(10)
print(random_array)

[0.55530649 0.02107562 0.04216417 0.48659018 0.10064244 0.78767471
 0.80158647 0.88043222 0.62104884 0.84040415]


In [ ]:
#Utwórz tablicę diagonal_array o wymiarach 5x5, która na przekątnej ma jedynki, a pozostałe wartości to zera. Hint: 
#Skorzystaj z metody eye

In [66]:
import numpy as np

diagonal_array = np.eye(5)
print(diagonal_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#Utwórz tablicę lucky_array o wymiarach 5x5 składającą się z samych trzynastek. Hint: Skorzystaj z metody full

In [67]:
lucky_array = np.full((5, 5), 13)
print(lucky_array)

[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]
