In [1]:
import numpy as np
import pandas as pd

In [ ]:
#1.  Napisz kod, który utworzy tablicę X zawierającą 10 wierszy i 5 kolumn o wartościach od -25 do 24. (skorzystaj z metody np.arange)

In [5]:
X = np.arange(-25,25)
X = X.reshape(10,5)
X

array([[-25, -24, -23, -22, -21],
       [-20, -19, -18, -17, -16],
       [-15, -14, -13, -12, -11],
       [-10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1],
       [  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [8]:
X_columns = X.shape[1]
X_columns

5

In [7]:
X_rows = X.shape[0]
X_rows

10

In [ ]:
#2. Utwórz kod, który utworzy tablicę ones, zawierającą tyle wierszy co X i jedną kolumnę wypełnioną jedynkami 
#(skorzystaj z metody np.ones oraz właściwości shape dla X)

In [13]:
Y = np.ones((X.shape[0],1))
Y

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
#3. Utwórz zmienną X_1, która powstaje przez doklejenie do zmiennej X kolumny pochodzącej z ones (skorzystaj z metody append przesyłając argument axis=1)

In [14]:
X_1 = np.append(X.copy(),Y,axis=1)
X_1

array([[-25., -24., -23., -22., -21.,   1.],
       [-20., -19., -18., -17., -16.,   1.],
       [-15., -14., -13., -12., -11.,   1.],
       [-10.,  -9.,  -8.,  -7.,  -6.,   1.],
       [ -5.,  -4.,  -3.,  -2.,  -1.,   1.],
       [  0.,   1.,   2.,   3.,   4.,   1.],
       [  5.,   6.,   7.,   8.,   9.,   1.],
       [ 10.,  11.,  12.,  13.,  14.,   1.],
       [ 15.,  16.,  17.,  18.,  19.,   1.],
       [ 20.,  21.,  22.,  23.,  24.,   1.]])

In [ ]:
#4. Utwórz wektor w, który ma tyle samo współrzędnych co ilość kolumn w zmiennej X_1. Wartości współrzędnych mają być wylosowane (skorzystaj z 
#np.random.rand)

In [15]:
w = np.random.rand(X_1.shape[1])
w

array([0.85838683, 0.25436604, 0.97800622, 0.97502068, 0.40476843,
       0.86189798])

In [ ]:
#5. Zdefiniuj funkcję predict przyjmującą jako argument x (będzie to jeden wiersz z tablicy X_1) i w, a w niej:
    #pomnóż przez siebie  wektor x i w (skorzystaj z metody np.dot). Wynik zapisz w zmiennej total_stimulation
    #napisz wyrażenie if, które będzie działać jak funkcja skoku i
        #dla total_stimulation > 0 zwróci 1
        #a w przeciwnym razie zwróci -1

In [16]:
def predict(x, w):
    total_simulation = np.dot(x,w)  #mnozenie matematyczne macierzy dot
    y_pred = 1 if total_simulation > 0 else -1
    return y_pred

In [ ]:
#6. Przetestuj działanie tej funkcji dla w i X_1[0,]


In [17]:
print(predict(X_1[0], w))

-1


In [ ]:
# 7. Napisz pętlę for, która dla każdego wiersza z X_1 wywoła funkcję predict. Wyniki tej funkcji na razie będziemy tylko wyświetlać

In [18]:
for row in X_1:
    y_pred = predict(row, w)
    print(y_pred)

-1
-1
-1
-1
-1
1
1
1
1
1
